FROM nvcr.io/nvidia/pytorch:24.10-py3 AS amsalas_pytorch_24
LABEL maintainer="Andres Salas-Espinales"

VOLUME /workspace

RUN pip install --upgrade pip && \
    pip install --no-cache-dir ipdb chainer opencv-python==4.5.5.64 \
	opencv-python-headless==4.5.5.64 easydict>=1.9 timm>=0.4.10 tensorboardX>=2.2  notebook ipywidgets \
	thop ptflops wandb pybase64 pytorch-toolbelt\   
    git+https://github.com/facebookresearch/segment-anything.git \
	-q jupyter_bbox_widget roboflow dataclasses-json supervision \
    pycocotools

RUN wget -q https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth -O /workspace/sam_vit_h_4b8939.pth


RUN apt-get update && \
    apt-get install -y --no-install-recommends tmux vim libgl1-mesa-glx && \
	rm -rf /var/lib/apt/lists/*

EXPOSE 8888

CMD ["/bin/bash"]

